document.getElementById("movieForm").addEventListener("submit", function (e) {
  e.preventDefault();

  const get = id => document.getElementById(id).value;

  const html = `
<!-- Generated by Moviflix Post -->
<div class="movie-container">
  <img src="${get('thumbnail')}" alt="${get('title')}" class="movie-thumbnail">

  <div class="watch-buttons">
    <a href="${get('watch')}" class="watch-btn" target="_blank">Watch Movie</a>
    <a href="${get('trailer')}" class="watch-btn" target="_blank">Watch Trailer</a>
  </div>

  <div class="movie-details">
    <h2>${get('title')}</h2>
    <ul>
      <li><strong>Quality:</strong> ${get('quality')}</li>
      <li><strong>Duration:</strong> ${get('duration')}</li>
      <li><strong>Language:</strong> ${get('language')}</li>
      <li><strong>Release Date:</strong> ${get('release')}</li>
      <li><strong>Plot:</strong> ${get('plot')}</li>
    </ul>
  </div>

  <div class="screenshots">
    <h3>Screenshots</h3>
    <div class="screenshots-grid">
      <img src="${get('ss1')}" alt="screenshot">
      <img src="${get('ss2')}" alt="screenshot">
      <img src="${get('ss3')}" alt="screenshot">
    </div>
  </div>

  <div class="download-section">
    <h3>Download Links</h3>
    <div class="download-links">
      <div class="row">
        <a href="${get('dl480')}">Download 480p</a>
        <a href="${get('dl720')}">Download 720p</a>
      </div>
      <div class="row">
        <a href="${get('dl1080')}">Download 1080p</a>
      </div>
    </div>
  </div>
</div>
`;

  document.getElementById("output").value = html;
});

document.getElementById("copyBtn").addEventListener("click", function () {
  const output = document.getElementById("output");
  output.select();
  document.execCommand("copy");
  alert("HTML code copied!");
});
